// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	OPENAI_API_KEY: string;
	AXIOM_TOKEN: string;
	AXIOM_DATASET_NAME: string;
	ENVIRONMENT: string;
}
